services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yam
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yam

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3200:3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: umbrella-insurance
      POSTGRES_USER: umbrella-insurance
      POSTGRES_DB: umbrella-insurance
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  umbrella-insurance-react-ui:
    build:
      context: .
      dockerfile: Dockerfile-umbrella-insurance-react-ui
    ports:
      - "3000:3000"
    volumes:
      - ui:/app
    deploy:
      resources:
        limits:
          memory: 1.5G
    #user: "spring:spring"
  umbrella-insurance-backend:
    build:
      context: .
      dockerfile: Dockerfile-umbrella-insurance-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: umbrella-insurance
      SPRING_DATASOURCE_PASSWORD: umbrella-insurance
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/umbrella-insurance
    deploy:
      resources:
        limits:
          memory: 1.5G
volumes:
  pgdata:
  ui: